### ISSUE TITLE
NoActiveSessionException for GetLocationData 

### ISSUE THREAD

**Issue by liefra** [AquaticInformatics/aquarius-sdk-java#141]
Since upgrading to `com.aquaticinformatics:aquarius.sdk:20.3.1` we are getting a **random exception** for the `/GetLocationData` call.

### Steps to Reproduce

````
private void createStatisticalDerivedTimeSeries() {
        Publish.LocationDataServiceRequest request =  new Publish.LocationDataServiceRequest();
        request.setLocationIdentifier("KH_Tramkok_[Tramkok]");
        aquariusClient.Publish.send(request);
    }
````

### Expected Behaviour

The GET requests succeeds and return the location data.

### Actual Behaviour

NoActiveSessionException thrown with the following error: 

````
{"ResponseStatus":{"ErrorCode":"NoActiveSessionException","Message":"Exception of type 'Server.Services.Authentication.Authentication.NoActiveSessionException' was thrown.","Errors":[]}}
````

The error doesn't occur every call, but often the first time after restarting the application.

Anybody else seeing this random error?

**Comment by DougSchmidt-AI** [comment]
This isn't a common failure I've seen from other customers, but there may be a few causes for this.

Your example code looks fine at first glance.

Can you download and run our [SystemSizer](https://github.com/AquaticInformatics/getting-started/releases/tag/SystemSizer) support tool on your AQTS app server? (not on the computer running your Java integration, but on the AQTS app server itself).

The above link includes detailed usage instructions.

Running that tool will collect the last 7 days of activity logs and will automatically upload it to our SFTP server and notify the AQUARIUS support team.

If your AQTS app server is blocked from connecting to the internet (many customer app servers are quite locked down), then there are special instructions on that linked page which explain how to use a 2-step process to get the ZIP archive uploaded to our SFTP server.

I think we will need to look at the activity logs to see when this server-side exception is being thrown.

My guesses about what might be going wrong are:

## 1) A threading issue

If your integration is making many concurrent requests across multiple threads, then perhaps the `aquariusClient` object, which implements  `AutoClosable`, has already had its `aquariusClient.close()` method invoked on another thread? This could happen by an explicit call to `aquariusClient.close()` or by wrapping the object in a `try (AquariusClient aquariusClient = AquariusClient.createConnectedClient("myserver", "myuser", "mypassword")) { ... }` try-with-resources block.

This would issue the `DELETE /session` request to end the authenticated session, and any further requests from other threads using the `aquariusClient` object would no longer have a valid authentication token.

## 2) A data-specific issue

I see in your example that your location identifier is `KH_Tramok_[Tramok]`. Those characters are all supposed to be valid characters for location identifiers, but the underscore `_` and square brackets `[` `]` are much less commonly used on customer systems. Maybe there is a data-driven server bug? This seems like a long-shot, but that is the issue?

## 3) Some other server bug?

If it is some other server-side bug, that should also be captured in the ZIP archive created by `SystemSizer`.

Once our support team has the ZIP archive, we should have a much clearer picture of what is going sideways.

**Comment by liefra** [comment]
@DougSchmidt-AI : Thank you for your fast and extensive reply.

### Response to 1) A threading issue:
I tried it with creating a new dedicated client session with the same errors occurring.

### Response to 2) A data-specific issue:
We are using this naming convention already more than 1 year without any problems. As this issue just happens randomly and sometimes, it is likely that it has nothing to do with that.

### Response to 3) Some other server bug?
We will run `SystemSizer` and connect with the support team.

Having said that, I noticed that we could optimise our code to reduce the number of parallel requests being send to the server. For now this solves the issue. 

I'm closing this issue now, as I think it is unlikely to be a problem with Java SDK itself. 

I'll reopen the issue in case I find more proof.

Thanks again
Frank
