### ISSUE TITLE
Correction Type Deserialization

### ISSUE THREAD

**Issue by zmoore-usgs** [AquaticInformatics/aquarius-sdk-java#49]
Hello,

We've been continuing to transition our application to the SDK and everything has been going smoothly aside from this issue that we ran into today. 

It seems that the SDK (we are currently using v17.4.3), when deserializing `CorrectionType` expects the USGS Multi Point correction type to be `UsgsMultiPoint` (see [here](https://github.com/AquaticInformatics/aquarius-sdk-java/blob/develop/src/main/java/com/aquaticinformatics/aquarius/sdk/timeseries/servicemodels/Publish.java#L5252)). 

Our Aquarius instance (currently v17.4.79.0) seems to output this correction type as `USGSMultiPoint` (`USGS` in all caps) when we fetch data via the JSON endpoints:

Example (with some parameters redacted/modified):
```
 "Corrections": [
    {
      "Type": "USGSMultiPoint",
      "StartTime": "2018-01-01T19:15:00.0000001-05:00",
      "EndTime": "2018-01-02T00:15:00.0000001-05:00",
      "Parameters": {
        "StartShiftPoints": [
          {
            "Value": 0,
            "Offset": -0.3
          }
        ],
        "UsgsType": "Set 3"
      },
      "ProcessingOrder": "PostProcessing"
    }
]
```

As a result, when the SDK consumes these corrections the type parameter ends up being set to `null` because `USGSMultiPoint` does not match `UsgsMultiPoint`. 

I thought that perhaps this was some sort of configuration change or override with our Aquarius instance so I attempted to generate DTOs from our running Aquarius instance using the `/Publish/v2/types` endpoints. When I executed `/Publish/v2/types/metadata` the allowable values list for `CorrectionType` did have `USGSMultiPoint` with `USGS` properly capitalized. However, when I executed `/Publish/v2/types/java` the generated enum for `CorrectionType` had it improperly capitalized as `UsgsMultiPoint`, so it seems generating DTOs from our live Aquarius instance will not work as a fix for this issue. Beyond manually modifying the SDK generated service model enum to the proper value (or perhaps modifying the generation script to replace `UsgsMultiPoint` with `USGSMultiPoint`) I don't think we really have another work-around for this issue at this point so it is blocking our full adoption of the SDK. 

Any help figuring this out would be greatly appreciated - thank you!

**Comment by schmidt4brains** [comment]
Hi Zachary, I'll take a look. That sounds like a bug.

The ServiceStack framework (including the ServiceStack.Java package used by the Java SDK) is supposed to be case-insensitive for enum serialization. That doesn't seem to be true.

**Comment by schmidt4brains** [comment]
This should be fixed by #51 

Version 18.5.2 should now be available in the Maven central repository.

**Comment by zmoore-usgs** [comment]
@schmidt4brains Testing this locally and it seems to have fixed the issue for us. Thank you!

**Comment by schmidt4brains** [comment]
Glad to hear this is fixed.

I've also raised https://github.com/ServiceStack/ServiceStack.Java/issues/29 to let the ServiceStack team know that they should pull in a similar change into their main project.
