### ISSUE TITLE
ExtendedAttributeFilter serialization seems to be incompatible with the API

### ISSUE THREAD

**Issue by zmoore-usgs** [AquaticInformatics/aquarius-sdk-java#52]
Hello,

I'm attempting to add an ExtendedAttributeFilter into a TimeSeriesUniqueIdListServiceRequest but seeing an error from Aquarius when I execute it. It seems like the API does not like the way that the ExtendedAttributeFilter gets serialized by GSON. When I examine the request URL being created by the SDK I see:

`.../AQUARIUS/Publish/v2/GetTimeSeriesUniqueIdList?extendedFilters=[{"FilterName":"PRIMARY_FLAG","FilterValue":"Primary"}]&locationIdentifier=...` (URL Encoded)

The response back from Aquarius is:

`Invalid extended attribute column name specified:`

If I manually remove the quotes from the serialized `extendedFilters` the request works as expected:

`.../AQUARIUS/Publish/v2/GetTimeSeriesUniqueIdList?extendedFilters=[{FilterName:PRIMARY_FLAG,FilterValue:Primary}]&locationIdentifier=...`

and I get a list of Time Series UIDs.

**Comment by schmidt4brains** [comment]
The 18.6.2 packaged has been deployed to the Maven Central Repository content distribution network.
It should start showing up in Maven dependency searches in a couple of hours.
