### ISSUE TITLE
Create Time Series Programmatically with SDK

### ISSUE THREAD

**Issue by IdeamDesa** [AquaticInformatics/aquarius-sdk-java#67]
Greetings, 
There are a method for create a timeSeries with SDK? i loooking in the API a method for this operation but not find them, thanks for you collab.

**Comment by DougSchmidt-AI** [comment]
There is sample code to perform this in the SDK wiki.

https://github.com/AquaticInformatics/aquarius-sdk-java/wiki/Creating-a-time-series
